apiVersion: toboggan.md/v1
kind: Template
metadata:
  name: k3s-aws-example-agent
  namespace: default
spec:
  patches:
    - path: 'metadata.name'
      target: cluster
      template: '{{variables.name}}'
    - path: 'spec.kubernetesVersion'
      target: cluster
      template: '{{variables.k3sVersion}}'
    - path: 'spec.cloudCredentialSecretName'
      target: cluster
      template: '{{variables.cloudCredential}}'
    - path: 'metadata.name'
      target: agent
      template: '{{variables.name}}-{{variables.poolName}}'
    - path: 'region'
      target: agent
      template: '{{variables.region}}'
    - path: 'vpcId'
      target: agent
      template: '{{variables.network.vpcId}}'
    - path: 'subnetId'
      target: agent
      template: '{{variables.network.subnetId}}'
    - path: 'instanceType'
      target: agent
      template: '{{variables.instanceType}}'
    - iterate: agent
      op: append
      path: 'spec.rkeConfig.agents'
      target: cluster
      template: |-
        name: {{iterate.overrides.poolName}}
        etcdRole: true
        controlPlaneRole: true
        workerRole: false
        hostnamePrefix: ''
        labels: {}
        quantity: {{iterate.overrides.quantity}}
        unhealthyNodeTimeout: 0m
        machineConfigRef:
          kind: Amazonec2Config
          name: {{iterate.resource.metadata.name}}
        drainBeforeDelete: true
    - path: 'metadata.name'
      target: workerPool
      template: '{{variables.name}}-{{variables.poolName}}'
    - path: 'region'
      target: workerPool
      template: '{{variables.region}}'
    - path: 'vpcId'
      target: workerPool
      template: '{{variables.network.vpcId}}'
    - path: 'subnetId'
      target: workerPool
      template: '{{variables.network.subnetId}}'
    - path: 'instanceType'
      target: workerPool
      template: '{{variables.instanceType}}'
    - iterate: workerPool
      op: append
      path: 'spec.rkeConfig.workerPools'
      target: cluster
      template: |-
        name: {{iterate.overrides.poolName}}
        etcdRole: false
        controlPlaneRole: false
        workerRole: true
        hostnamePrefix: ''
        labels: {}
        quantity: {{iterate.overrides.quantity}}
        unhealthyNodeTimeout: 0m
        machineConfigRef:
          kind: Amazonec2Config
          name: {{iterate.resource.metadata.name}}
        drainBeforeDelete: true
  resources:
    - name: cluster
      k8s-type: provisioning.cattle.io.cluster
      max: 1
      min: 1
      required: true
      template: |-
        type: provisioning.cattle.io.cluster
        kind: Cluster
        apiVersion: provisioning.cattle.io/v1
        metadata:
          namespace: fleet-default
          name: REPLACE_ME
        spec:
          rkeConfig:
            chartValues: {}
            upgradeStrategy:
              controlPlaneConcurrency: '1'
              controlPlaneDrainOptions:
                deleteEmptyDirData: true
                disableEviction: false
                enabled: false
                force: false
                gracePeriod: -1
                ignoreDaemonSets: true
                skipWaitForDeleteTimeoutSeconds: 0
                timeout: 120
              workerConcurrency: '1'
              workerDrainOptions:
                deleteEmptyDirData: true
                disableEviction: false
                enabled: false
                force: false
                gracePeriod: -1
                ignoreDaemonSets: true
                skipWaitForDeleteTimeoutSeconds: 0
                timeout: 120
            dataDirectories:
              systemAgent: ''
              provisioning: ''
              k8sDistro: ''
            machineGlobalConfig:
              disable-cloud-controller: false
              disable-kube-proxy: false
              disable-scheduler: false
              etcd-expose-metrics: false
              disable-apiserver: false
              disable-controller-manager: false
              disable-etcd: false
              disable-network-policy: false
              etcd-s3-bucket-lookup-type: auto
              secrets-encryption: false
              secrets-encryption-provider: aescbc
            machineSelectorConfig:
              - config:
                  protect-kernel-defaults: false
                  selinux: false
                  docker: false
            etcd:
              disableSnapshots: false
              s3: null
              snapshotRetention: 5
              snapshotScheduleCron: 0 */5 * * *
            registries:
              configs: {}
              mirrors: {}
          machineSelectorConfig:
            - config: {}
          kubernetesVersion: v1.34.2+k3s1
          defaultPodSecurityAdmissionConfigurationTemplateName: ''
          localClusterAuthEndpoint:
            enabled: false
          cloudCredentialSecretName: REPLACE_ME
    - name: agent
      k8s-type: rke-machine-config.cattle.io.amazonec2config
      min: 1
      max: 3
      required: true
      variables:
      - name: poolName
        required: true
        schema:
          openAPIV3Schema:
            description: Name of the agent pool. This will be combined with the name of the cluster to ensure all pools have names unique within the Rancher instance.
            type: string
      - name: agentQuantity
        metadata:
          annotations:
            toboggan.md/section: Default Machine Pool Configuration
        required: true
        schema:
          openAPIV3Schema:
            default: 3
            type: integer
            minimum: 3
      overrides:
      - region
      - network
      - instanceType
      template: |-
        kind: Amazonec2Config
        apiVersion: rke-machine-config.cattle.io/v1
        instanceType: t3a.medium
        metadata:
          annotations: {}
          labels: {}
          namespace: fleet-default
        openPort: []
        region: us-west-2
        securityGroup:
          - rancher-nodes
        securityGroupReadonly: false
        zone: a
        type: rke-machine-config.cattle.io.amazonec2config
    - name: workerPool
      k8s-type: rke-machine-config.cattle.io.amazonec2config
      min: 1
      max: 5
      required: true
      variables:
      - name: poolName
        required: true
        schema:
          openAPIV3Schema:
            description: Name of the worker pool. This will be combined with the name of the cluster to ensure all pools have names unique within the Rancher instance.
            type: string
      overrides:
      - etcdRole
      - controlPlaneRole
      - workerRole
      - quantity
      - region
      - network
      - instanceType
      template: |-
        kind: Amazonec2Config
        apiVersion: rke-machine-config.cattle.io/v1
        instanceType: t3a.medium
        metadata:
          annotations: {}
          labels: {}
          namespace: fleet-default
        openPort: []
        region: us-west-2
        securityGroup:
          - rancher-nodes
        securityGroupReadonly: false
        zone: a
        type: rke-machine-config.cattle.io.amazonec2config
  resourceDefaults:
    - name: agent
    - name: cluster
    - name: workerPool
  variables:
    - metadata:
        annotations:
          toboggan.md/component: 'TemplateK3sVersion'
      name: k3sVersion
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - metadata:
        annotations:
          toboggan.md/component: 'TemplateCloudCredentialAws'
          toboggan.md/widest: 'true'
      name: cloudCredential
      required: true
      schema:
        openAPIV3Schema:
          description: Rancher cloud credentials allow your Rancher server to communicate with and request compute resources from Amazon Web Services. 
          type: string
          default: ''
    - name: name
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: clustermembership
      metadata:
        annotations:
          toboggan.md/component: TemplateClusterMembership
          toboggan.md/section: Cluster Membership
          toboggan.md/widest: 'true'
      required: false
      schema:
        openAPIV3Schema:
          type: string
    - name: quantity
      metadata:
        annotations:
          toboggan.md/section: Default Machine Pool Configuration
      required: true
      schema:
        openAPIV3Schema:
          type: integer
          default: 1
          maximum: 5
    - name: region
      metadata:
        annotations:
          toboggan.md/section: Default Machine Pool Configuration
          toboggan.md/group: AWS Configuration
          toboggan.md/component: TemplateAwsRegion
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: 'us-west-2'
    - name: network
      metadata:
        annotations:
          toboggan.md/section: Default Machine Pool Configuration
          toboggan.md/group: AWS Configuration
          toboggan.md/component: TemplateAwsVpc
      required: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            vpcId:
              type: string
            subnetId:
              type: string
    - name: instanceType
      metadata:
        annotations:
          toboggan.md/section: Default Machine Pool Configuration
          toboggan.md/group: AWS Configuration
          toboggan.md/component: TemplateAwsInstanceType
          toboggan.md/docs: https://aws.amazon.com/ec2/instance-types/
          toboggan.md/highlight: info
          toboggan.md/label: EC2 Instance
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: t3a.medium
          description: K3s server nodes should have at least 2CPU and 2GB RAM. Agent nodes should have at least 1CPU and 512MB RAM.
          enum:
            - t3a.micro
            - t3a.small
            - t3a.medium
            - t3a.large

          
