apiVersion: toboggan.md/v1
kind: Template
metadata:
  name: k3s-aws-example
  namespace: default
spec:
  patches:
    - path: 'metadata.name'
      target: cluster
      template: '{{variables.name}}'
    - path: 'spec.kubernetesVersion'
      target: cluster
      template: '{{variables.k3sVersion}}'
    - path: 'spec.cloudCredentialSecretName'
      target: cluster
      template: '{{variables.cloudCredential}}'
    - path: 'metadata.name'
      target: machinePool
      template: '{{variables.name}}-{{variables.poolName}}'
    - iterate: machinePool
      op: append
      path: 'spec.rkeConfig.machinePools'
      target: cluster
      template: |-
        name: {{iterate.overrides.poolName}}
        etcdRole: {{iterate.overrides.etcdRole}}
        controlPlaneRole: {{iterate.overrides.controlPlaneRole}}
        workerRole: {{iterate.overrides.workerRole}}
        hostnamePrefix: ''
        labels: {}
        quantity: {{iterate.overrides.quantity}}
        unhealthyNodeTimeout: 0m
        machineConfigRef:
          kind: Amazonec2Config
          name: {{iterate.resource.metadata.name}}
        drainBeforeDelete: true
  resources:
    - name: cluster
      k8s-type: provisioning.cattle.io.cluster
      max: 1
      min: 1
      required: true
      template: |-
        type: provisioning.cattle.io.cluster
        kind: Cluster
        apiVersion: provisioning.cattle.io/v1
        metadata:
          namespace: fleet-default
          name: REPLACE_ME
        spec:
          rkeConfig:
            chartValues: {}
            upgradeStrategy:
              controlPlaneConcurrency: '1'
              controlPlaneDrainOptions:
                deleteEmptyDirData: true
                disableEviction: false
                enabled: false
                force: false
                gracePeriod: -1
                ignoreDaemonSets: true
                skipWaitForDeleteTimeoutSeconds: 0
                timeout: 120
              workerConcurrency: '1'
              workerDrainOptions:
                deleteEmptyDirData: true
                disableEviction: false
                enabled: false
                force: false
                gracePeriod: -1
                ignoreDaemonSets: true
                skipWaitForDeleteTimeoutSeconds: 0
                timeout: 120
            dataDirectories:
              systemAgent: ''
              provisioning: ''
              k8sDistro: ''
            machineGlobalConfig:
              disable-cloud-controller: false
              disable-kube-proxy: false
              disable-scheduler: false
              etcd-expose-metrics: false
              disable-apiserver: false
              disable-controller-manager: false
              disable-etcd: false
              disable-network-policy: false
              etcd-s3-bucket-lookup-type: auto
              secrets-encryption: false
              secrets-encryption-provider: aescbc
            machineSelectorConfig:
              - config:
                  protect-kernel-defaults: false
                  selinux: false
                  docker: false
            etcd:
              disableSnapshots: false
              s3: null
              snapshotRetention: 5
              snapshotScheduleCron: 0 */5 * * *
            registries:
              configs: {}
              mirrors: {}
          machineSelectorConfig:
            - config: {}
          kubernetesVersion: v1.34.2+k3s1
          defaultPodSecurityAdmissionConfigurationTemplateName: ''
          localClusterAuthEndpoint:
            enabled: false
          cloudCredentialSecretName: REPLACE_ME
    - name: machinePool
      k8s-type: rke-machine-config.cattle.io.amazonec2config
      min: 1
      max: 9999
      required: true
      variables:
      - name: poolName
        required: true
        schema:
          openAPIV3Schema:
            description: Name of the machine pool. This will be combined with the name of the cluster to ensure all pools have names unique within the Rancher instance.
            type: string
      overrides:
      - etcdRole
      - controlPlaneRole
      - workerRole
      - quantity
      template: |-
        kind: Amazonec2Config
        apiVersion: rke-machine-config.cattle.io/v1
        instanceType: t3a.medium
        metadata:
          annotations: {}
          labels: {}
          namespace: fleet-default
        openPort: []
        region: us-west-2
        securityGroup:
          - rancher-nodes
        securityGroupReadonly: false
        subnetId: subnet-02e4caf6f4ee75111
        vpcId: vpc-07cdd250a077f6773
        zone: a
        type: rke-machine-config.cattle.io.amazonec2config
  resourceDefaults:
    - name: machinePool
    - name: cluster
  variables:
    - metadata:
        annotations:
          toboggan.md/component: 'TemplateK3sVersion'
      name: k3sVersion
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - metadata:
        annotations:
          toboggan.md/component: 'TemplateCloudCredentialAws'
          toboggan.md/widest: 'true'
      name: cloudCredential
      required: true
      schema:
        openAPIV3Schema:
          description: Rancher cloud credentials allow your Rancher server to communicate with and request compute resources from Amazon Web Services. 
          type: string
    - name: name
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: clustermembership
      metadata:
        annotations:
          toboggan.md/component: TemplateClusterMembership
          toboggan.md/section: Cluster Membership
          toboggan.md/widest: 'true'
      required: false
      schema:
        openAPIV3Schema:
          type: string
    - name: etcdRole
      metadata:
        annotations:
          toboggan.md/section: Machine Pools
      required: true
      schema:
        openAPIV3Schema:
          type: boolean
          default: true
    - name: controlPlaneRole
      metadata:
        annotations:
          toboggan.md/section: Machine Pools
      required: true
      schema:
        openAPIV3Schema:
          type: boolean
          default: true
    - name: workerRole
      metadata:
        annotations:
          toboggan.md/section: Machine Pools
      required: true
      schema:
        openAPIV3Schema:
          type: boolean
          default: true
    - name: quantity
      metadata:
        annotations:
          toboggan.md/section: Machine Pools
      required: true
      schema:
        openAPIV3Schema:
          type: integer
          default: 1
          
