apiVersion: toboggan.md/v1
kind: Template
metadata:
  name: k3s-aws-example
  namespace: default
spec:
  patches:
    - path: 'metadata.name'
      target: cluster
      template: '{{variables.name}}'
    - path: 'metadata.name'
      target: machinePool
      template: '{{variables.name}}'
  resources:
    - name: cluster
      k8s-type: provisioning.cattle.io.cluster
      max: 1
      min: 1
      required: true
      template: |-
        type: provisioning.cattle.io.cluster
        metadata:
          namespace: fleet-default
          name: REPLACE_ME
        spec:
          rkeConfig:
            chartValues: {}
            upgradeStrategy:
              controlPlaneConcurrency: '1'
              controlPlaneDrainOptions:
                deleteEmptyDirData: true
                disableEviction: false
                enabled: false
                force: false
                gracePeriod: -1
                ignoreDaemonSets: true
                skipWaitForDeleteTimeoutSeconds: 0
                timeout: 120
              workerConcurrency: '1'
              workerDrainOptions:
                deleteEmptyDirData: true
                disableEviction: false
                enabled: false
                force: false
                gracePeriod: -1
                ignoreDaemonSets: true
                skipWaitForDeleteTimeoutSeconds: 0
                timeout: 120
            dataDirectories:
              systemAgent: ''
              provisioning: ''
              k8sDistro: ''
            machineGlobalConfig:
              disable-cloud-controller: false
              disable-kube-proxy: false
              disable-scheduler: false
              etcd-expose-metrics: false
              disable-apiserver: false
              disable-controller-manager: false
              disable-etcd: false
              disable-network-policy: false
              etcd-s3-bucket-lookup-type: auto
              secrets-encryption: false
              secrets-encryption-provider: aescbc
            machineSelectorConfig:
              - config:
                  protect-kernel-defaults: false
                  selinux: false
                  docker: false
            etcd:
              disableSnapshots: false
              s3: null
              snapshotRetention: 5
              snapshotScheduleCron: 0 */5 * * *
            registries:
              configs: {}
              mirrors: {}
            machinePools:
              - name: pool1
                etcdRole: true
                controlPlaneRole: true
                workerRole: true
                hostnamePrefix: ''
                labels: {}
                quantity: 1
                unhealthyNodeTimeout: 0m
                machineConfigRef:
                  kind: Amazonec2Config
                  name: REPLACE_ME
                drainBeforeDelete: true
          machineSelectorConfig:
            - config: {}
          kubernetesVersion: REPLACE_ME
          defaultPodSecurityAdmissionConfigurationTemplateName: ''
          localClusterAuthEndpoint:
            enabled: false
          cloudCredentialSecretName: REPLACE_ME
    - name: machinePool
      k8s-type: rke-machine-config.cattle.io.amazonec2config
      min: 1
      max: 9999
      required: true
      overrides:
      - 'name'
      template: |-
        instanceType: t3a.medium
        metadata:
          annotations: {}
          generateName: REPLACE_ME
          labels: {}
          namespace: fleet-default
          ownerReferences: []
        openPort: []
        region: REPLACE_ME
        securityGroup:
          - rancher-nodes
        securityGroupReadonly: false
        subnetId: REPLACE_ME
        vpcId: REPLACE_ME
        zone: REPLACE_ME
        type: rke-machine-config.cattle.io.amazonec2config
  resourceDefaults:
    - name: machinePool
      overrides:
      - name: name
        value: test-value-please-ignore
    - name: cluster
  variables:
    - name: name
      required: true
      schema:
        openAPIV3Schema:
          description: metadata.name
          type: string
    - metadata:
        annotations:
          toboggan.md/component: 'TemplateNamespace'
      name: namescape
      required: true
      schema:
        openAPIV3Schema:
          description: metadata.name
          type: string