apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templates.toboggan.md
spec:
  group: toboggan.md
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: 
              type: object
              properties:
                variables:
                  type: array
                  items:
                    description: |-
                      ClusterClassVariable defines a variable which can
                      be configured in the Cluster topology and used in patches.
                    properties:
                      metadata:
                        description: >-
                          metadata is the metadata of a variable.

                          It can be used to add additional data for higher level
                          tools
                        properties:
                          annotations:
                            additionalProperties:
                              type: string
                            description: >-
                              annotations is an unstructured key value map that
                              can be used to store and

                              retrieve arbitrary metadata.

                              They are not queryable.
                            type: object
                          labels:
                            additionalProperties:
                              type: string
                            description: >-
                              labels is a map of string keys and values that can
                              be used to organize and categorize

                              (scope and select) variables.
                            type: object
                        type: object
                      name:
                        description: name of the variable.
                        maxLength: 256
                        minLength: 1
                        type: string
                      required:
                        description: >-
                          required specifies if the variable is required.

                          Note: this applies to the variable as a whole and thus
                          the

                          top-level object defined in the schema. If nested
                          fields are

                          required, this will be specified inside the schema.
                        type: boolean
                      schema:
                        description: schema defines the schema of the variable.
                        properties:
                          openAPIV3Schema:
                            description: >-
                              openAPIV3Schema defines the schema of a variable
                              via OpenAPI v3

                              schema. The schema is a subset of the schema used
                              in

                              Kubernetes CRDs.
                            properties:
                              additionalProperties:
                                description: >-
                                  additionalProperties specifies the schema of
                                  values in a map (keys are always strings).

                                  NOTE: Can only be set if type is object.

                                  NOTE: AdditionalProperties is mutually
                                  exclusive with Properties.

                                  NOTE: This field uses PreserveUnknownFields
                                  and Schemaless,

                                  because recursive validation is not possible.
                                x-kubernetes-preserve-unknown-fields: true
                              allOf:
                                description: >-
                                  allOf specifies that the variable must
                                  validate against all of the subschemas in the
                                  array.

                                  NOTE: This field uses PreserveUnknownFields
                                  and Schemaless,

                                  because recursive validation is not possible.
                                x-kubernetes-preserve-unknown-fields: true
                              anyOf:
                                description: >-
                                  anyOf specifies that the variable must
                                  validate against one or more of the subschemas
                                  in the array.

                                  NOTE: This field uses PreserveUnknownFields
                                  and Schemaless,

                                  because recursive validation is not possible.
                                x-kubernetes-preserve-unknown-fields: true
                              default:
                                description: |-
                                  default is the default value of the variable.
                                  NOTE: Can be set for all types.
                                x-kubernetes-preserve-unknown-fields: true
                              description:
                                description: >-
                                  description is a human-readable description of
                                  this variable.
                                maxLength: 4096
                                minLength: 1
                                type: string
                              enum:
                                description: >-
                                  enum is the list of valid values of the
                                  variable.

                                  NOTE: Can be set for all types.
                                items:
                                  x-kubernetes-preserve-unknown-fields: true
                                maxItems: 100
                                type: array
                              example:
                                description: example is an example for this variable.
                                x-kubernetes-preserve-unknown-fields: true
                              exclusiveMaximum:
                                description: >-
                                  exclusiveMaximum specifies if the Maximum is
                                  exclusive.

                                  NOTE: Can only be set if type is integer or
                                  number.
                                type: boolean
                              exclusiveMinimum:
                                description: >-
                                  exclusiveMinimum specifies if the Minimum is
                                  exclusive.

                                  NOTE: Can only be set if type is integer or
                                  number.
                                type: boolean
                              format:
                                description: >-
                                  format is an OpenAPI v3 format string. Unknown
                                  formats are ignored.

                                  For a list of supported formats please see:
                                  (of the k8s.io/apiextensions-apiserver version
                                  we're currently using)

                                  https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apiserver/validation/formats.go

                                  NOTE: Can only be set if type is string.
                                maxLength: 32
                                minLength: 1
                                type: string
                              items:
                                description: >-
                                  items specifies fields of an array.

                                  NOTE: Can only be set if type is array.

                                  NOTE: This field uses PreserveUnknownFields
                                  and Schemaless,

                                  because recursive validation is not possible.
                                x-kubernetes-preserve-unknown-fields: true
                              maxItems:
                                description: >-
                                  maxItems is the max length of an array
                                  variable.

                                  NOTE: Can only be set if type is array.
                                format: int64
                                type: integer
                              maxLength:
                                description: >-
                                  maxLength is the max length of a string
                                  variable.

                                  NOTE: Can only be set if type is string.
                                format: int64
                                type: integer
                              maxProperties:
                                description: >-
                                  maxProperties is the maximum amount of entries
                                  in a map or properties in an object.

                                  NOTE: Can only be set if type is object.
                                format: int64
                                type: integer
                              maximum:
                                description: >-
                                  maximum is the maximum of an integer or number
                                  variable.

                                  If ExclusiveMaximum is false, the variable is
                                  valid if it is lower than, or equal to, the
                                  value of Maximum.

                                  If ExclusiveMaximum is true, the variable is
                                  valid if it is strictly lower than the value
                                  of Maximum.

                                  NOTE: Can only be set if type is integer or
                                  number.
                                format: int64
                                type: integer
                              minItems:
                                description: >-
                                  minItems is the min length of an array
                                  variable.

                                  NOTE: Can only be set if type is array.
                                format: int64
                                type: integer
                              minLength:
                                description: >-
                                  minLength is the min length of a string
                                  variable.

                                  NOTE: Can only be set if type is string.
                                format: int64
                                type: integer
                              minProperties:
                                description: >-
                                  minProperties is the minimum amount of entries
                                  in a map or properties in an object.

                                  NOTE: Can only be set if type is object.
                                format: int64
                                type: integer
                              minimum:
                                description: >-
                                  minimum is the minimum of an integer or number
                                  variable.

                                  If ExclusiveMinimum is false, the variable is
                                  valid if it is greater than, or equal to, the
                                  value of Minimum.

                                  If ExclusiveMinimum is true, the variable is
                                  valid if it is strictly greater than the value
                                  of Minimum.

                                  NOTE: Can only be set if type is integer or
                                  number.
                                format: int64
                                type: integer
                              not:
                                description: >-
                                  not specifies that the variable must not
                                  validate against the subschema.

                                  NOTE: This field uses PreserveUnknownFields
                                  and Schemaless,

                                  because recursive validation is not possible.
                                x-kubernetes-preserve-unknown-fields: true
                              oneOf:
                                description: >-
                                  oneOf specifies that the variable must
                                  validate against exactly one of the subschemas
                                  in the array.

                                  NOTE: This field uses PreserveUnknownFields
                                  and Schemaless,

                                  because recursive validation is not possible.
                                x-kubernetes-preserve-unknown-fields: true
                              pattern:
                                description: >-
                                  pattern is the regex which a string variable
                                  must match.

                                  NOTE: Can only be set if type is string.
                                maxLength: 512
                                minLength: 1
                                type: string
                              properties:
                                description: >-
                                  properties specifies fields of an object.

                                  NOTE: Can only be set if type is object.

                                  NOTE: Properties is mutually exclusive with
                                  AdditionalProperties.

                                  NOTE: This field uses PreserveUnknownFields
                                  and Schemaless,

                                  because recursive validation is not possible.
                                x-kubernetes-preserve-unknown-fields: true
                              required:
                                description: >-
                                  required specifies which fields of an object
                                  are required.

                                  NOTE: Can only be set if type is object.
                                items:
                                  maxLength: 256
                                  minLength: 1
                                  type: string
                                maxItems: 1000
                                type: array
                              type:
                                description: >-
                                  type is the type of the variable.

                                  Valid values are: object, array, string,
                                  integer, number or boolean.
                                enum:
                                  - object
                                  - array
                                  - string
                                  - integer
                                  - number
                                  - boolean
                                type: string
                              uniqueItems:
                                description: >-
                                  uniqueItems specifies if items in an array
                                  must be unique.

                                  NOTE: Can only be set if type is array.
                                type: boolean
                              x-kubernetes-int-or-string:
                                description: >-
                                  x-kubernetes-int-or-string specifies that this
                                  value is

                                  either an integer or a string. If this is
                                  true, an empty

                                  type is allowed and type as child of anyOf is
                                  permitted

                                  if following one of the following patterns:


                                  1) anyOf:
                                     - type: integer
                                     - type: string
                                  2) allOf:
                                     - anyOf:
                                       - type: integer
                                       - type: string
                                     - ... zero or more
                                type: boolean
                              x-kubernetes-preserve-unknown-fields:
                                description: >-
                                  x-kubernetes-preserve-unknown-fields allows
                                  setting fields in a variable object

                                  which are not defined in the variable schema.
                                  This affects fields recursively,

                                  except if nested properties or
                                  additionalProperties are specified in the
                                  schema.
                                type: boolean
                            type: object
                        required:
                          - openAPIV3Schema
                        type: object
                    required:
                      - name
                      - required
                      - schema
                    type: object
                resources:
                  type: array
                  items:
                    type: object
                    properties:
                      k8s-type:
                        type: string
                      min:
                        type: integer
                      max:
                        type: integer
                      required:
                        type: boolean
                      template:
                        type: string
                      overrides:
                        type: array
                        items:
                          type: string
                patches:
                  type: array
                  items:
                    type: object
                    properties:
                      target:
                        description: Which resources to apply this patch to. This must match at least one k8s-type in resources
                        type: string
                      path:
                        description: Where in the resource to apply the patch
                        type: string
                      template:
                        description: Patch to be applied at the specified path. This field accepts handlebars templates. 
                        type: string
  scope: Namespaced
  names:
    plural: templates
    singular: template
    kind: Template